## YAML Template.
---
ip: "--"
port : "--"
info:
- modulName: "---"
  password: "---"
  username: "----"
  pcpassword : "---"
  catalinaHome : "home/cabinet/apache-tomcat-8.0.39"
  path: "/home/ubuntu/eclipse_project/workspace"
  usergroup: "---" 
  multipletomcat : "false"
- modulName: "--"
  password: "----"
  username: "---"
  pcpassword : "----"
  catalinaHome : "home/"
  path: "/home/ubuntu/eclipse_project"
  usergroup: "--"
  multipletomcat : "false"
- modulName: "--"
  password: "---"
  username: "---"
  pcpassword : "----"
  catalinaHome : "/home/cabinet/apache-tomcat-8.0.39"
  path: "/home/ubuntu/eclipse_project/workspace"
  usergroup: "cabinet"
  multipletomcat : "false"
- modulName: "----"
  password: "---"
  username: "----"
  pcpassword : "----"
  catalinaHome : "/home/proxy/apache-tomcat-8.0.39"
  path: "/home/ubuntu/eclipse_project/workspace/"
  usergroup: "---"
  multipletomcat : "false"
